name: Python CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip python-coveralls coverage mock nose pyflakes pycodestyle
      - name: Ensure that code is poppin fresh (Check Code Style)
        run: |
          pycodestyle -v --ignore=E501,E722 bitmath/__init__.py tests/*.py
      - name: Flakey or Crunchy (Run PyFlakes)
        run: |
          pyflakes bitmath/__init__.py tests/*.py
      - name: Verify Test Case Names Unique
        run: |
          ./tests/test_unique_testcase_names.sh
      - name: Run Unit Tests
        run: |
          nosetests -v tests/
